enum error_codes {
  INIT_SDL_INIT,
  INIT_SDL_CREATE_WINDOW,
  INIT_SDL_CREATE_RENDERER,
  INIT_SDL_SET_RENDERER_DRAW_COLOR,
  INIT_IMG_INIT,
  LOADMEDIA_LOAD_TEXTURE,
  MAIN_INIT,
  MAIN_LOAD_MEDIA,
};

int handle_error( int errno, const char* err_msg );
